<a href="https://colab.research.google.com/github/Dipak22/DeepLearning/blob/master/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [3]:
## Introduction to tensors

### Creating tensors

In [10]:
#scalar
scalar = torch.tensor(7.0)
scalar

tensor(7.)

In [11]:
type(scalar.item())

float

In [12]:
vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [16]:
vec.shape

torch.Size([2])

In [18]:
scalar.ndim

0

In [19]:
#Matrix
mat = torch.tensor([[7,8],
                    [9,10]])
mat

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
mat.shape

torch.Size([2, 2])

In [22]:
type(mat)

torch.Tensor

In [30]:
type(mat[1,0].item())

int

In [32]:
d3 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [2,4,5]]])
d3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [34]:
d3.shape

torch.Size([1, 3, 3])

### Random Tensors
Why random tensors?

`start with rand numbers -> look at data->update random tenors->repeat`

In [35]:
random_tensor = torch.randn(3,4)
random_tensor

tensor([[-1.8353, -0.1745,  0.9140,  1.0909],
        [ 0.4037,  1.0130,  0.6531, -1.2988],
        [ 0.9684, -0.4770,  0.2882,  0.7276]])

In [37]:
random_tensor.shape

torch.Size([3, 4])

In [39]:
random_image_size_tensor = torch.rand(3,224,224)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [40]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
zero * random_tensor

tensor([[-0., -0., 0., 0.],
        [0., 0., 0., -0.],
        [0., -0., 0., 0.]])

In [42]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

In [44]:
ones * random_tensor

tensor([[-1.8353, -0.1745,  0.9140,  1.0909],
        [ 0.4037,  1.0130,  0.6531, -1.2988],
        [ 0.9684, -0.4770,  0.2882,  0.7276]])

### Creating a range of tensors and tensors like

In [51]:
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
ten_rands = torch.randn_like(input=ten_ones, dtype=torch.float32)
ten_rands

tensor([ 0.7229, -0.3646, -0.1035,  0.4428, -0.6019,  0.8264, -0.4765,  0.0405,
        -0.6135,  0.3072])

In [69]:
ten_rands.shape

torch.Size([10])

### Tensor datatypes

In [66]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [67]:
float_32_tensor.dtype

torch.float32

In [70]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [72]:
new_float = float_16_tensor * float_32_tensor

In [73]:
new_float.dtype

torch.float32

In [74]:
new_float

tensor([ 9., 36., 81.])

In [81]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [84]:
x = int_32_tensor * float_32_tensor

In [85]:
x, x.shape, x.dtype

(tensor([ 9., 36., 81.]), torch.Size([3]), torch.float32)

### Get information from tensors.
1. tensor.dtype
2. tensor.shape
3. tensor.device

In [86]:
x.device

device(type='cpu')

### Manipulating tensors(tensor operations)
1. Addition
2. Subtraction
3. Multiplication(element-wise)
4. Division
5. Matrix Multiplication

In [87]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor, tensor + 10

(tensor([1, 2, 3]), tensor([11, 12, 13]))

In [88]:
# multiply tensor by 10
tensor, tensor * 10

(tensor([1, 2, 3]), tensor([10, 20, 30]))

In [89]:
tensor, tensor -10

(tensor([1, 2, 3]), tensor([-9, -8, -7]))

In [90]:
# try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [91]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [92]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [93]:
torch.divide(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

In [94]:
tensor, tensor/2

(tensor([1, 2, 3]), tensor([0.5000, 1.0000, 1.5000]))

### Matrix multiplication

In [107]:
%%time
(tensor * tensor).sum()

CPU times: user 176 µs, sys: 6 µs, total: 182 µs
Wall time: 188 µs


tensor(14)

In [109]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 555 µs, sys: 0 ns, total: 555 µs
Wall time: 423 µs


tensor(14)

In [110]:
%%time
tensor @ tensor

CPU times: user 955 µs, sys: 1 µs, total: 956 µs
Wall time: 770 µs


tensor(14)

In [112]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])


In [114]:
tensor_B = tensor_B.T
tensor_B.shape

torch.Size([2, 3])

In [116]:
torch.mm(tensor_A,tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc

In [134]:
#create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [120]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [121]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [125]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [126]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [127]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [131]:
tensor_A.sum(dim =-1)

tensor([ 3,  7, 11])

In [135]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [137]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [138]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqezzing tensors

* Reshaping - reshapes the tensors to a defined shape
* View - Return a view of an input tensor of a certain shape but keeps the smae memory.
* stacking - combine multiple tensors along a given dimension
* unsqueeze add a 1 dimension to a target tensor
* Return a view, by swapping the dimensions.

In [146]:
x = torch.arange(1.,13.)

In [145]:
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [147]:
x_reshaped = x.reshape(2,2,3)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]]]),
 torch.Size([2, 2, 3]))

In [148]:
#change the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [149]:
#changing z , changes x
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [152]:
#stack tensors on top pf each other
x_stacked = torch.stack([x,x,x,x], dim =1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [153]:
x_stacked.shape

torch.Size([12, 4])

In [165]:
x_squeezed = x_stacked.unsqueeze(dim=2)

In [166]:
#permute
x_squeezed.shape, x_squeezed.permute(2,0,1).shape

(torch.Size([12, 4, 1]), torch.Size([1, 12, 4]))

## Indexing

In [167]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [168]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [169]:
x[0][0]

tensor([1, 2, 3])

In [172]:
x[0,0,0]

tensor(1)

In [173]:
x[0,1,1]

tensor(5)

In [174]:
x[0,2,2]

tensor(9)

In [178]:
x[:,:,1]

tensor([[2, 5, 8]])

In [180]:
x[:,1,1].shape

torch.Size([1])

In [184]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [185]:
array[0] = 10
array, tensor

(array([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [188]:
# tensor to numpy array
tensor = torch.ones(7).type(torch.float64)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64),
 array([1., 1., 1., 1., 1., 1., 1.]))

## Reproducibility

In [191]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C== random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
!nvidia-smi

Mon Mar  3 20:00:23 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## check GPU access for pytorch

In [2]:
import torch
torch.cuda.is_available()

True

In [5]:
#Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [6]:
# count number of gpus
torch.cuda.device_count()

1

In [9]:
tensor = torch.tensor([1,2,3], device=device)
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [8]:
#Move tensor to GPU
tensor_on_gpu = tensor.to(device=device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
#Moving tensors back to cpu
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')